; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3box]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32s3box
framework = arduino
board_build.arduino.partitions = esp_sr_16_large.csv
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    Bodmer/TJpg_Decoder@^1.0.8
lib_ignore =
    ESP_SR
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_USE_WAKENET=1
    -DCONFIG_USE_MULTINET=1
    -I include
    -I lib/Mylibrary
    -D LV_CONF_INCLUDE_SIMPLE
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 5000
debug_extra_cmds = 
    set remotetimeout 120
    set tcp connect-timeout 120
    set tcp auto-retry on
    ; set debug remote 1
    monitor reset halt